# gnome-terminal profile configuration
#
# $ dconf help
# $ dconf dump /org/gnome/terminal/legacy/profiles:/ > gnome-terminal-profiles.conf

[/]
default='65c2a0d6-c24c-4a21-9870-2548ab4aba70'
list=['b1dcc9dd-5262-4d8d-a863-c897e6d979b9', '65c2a0d6-c24c-4a21-9870-2548ab4aba70']

[:65c2a0d6-c24c-4a21-9870-2548ab4aba70]
audible-bell=false
background-color='rgb(22,22,22)'
cell-height-scale=1.05
cell-width-scale=1.1000000000000001
exit-action='close'
font='Ubuntu Sans Mono 15'
foreground-color='rgb(170,187,187)'
use-system-font=false
use-theme-colors=false
visible-name='Boulder'

[:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
visible-name='Ubuntu'
